### ISSUE TITLE
[JOSS REVIEW]: installation instructions from github

### ISSUE THREAD

**Issue by tomsing1** [anwarbio/bioassays#2]
Thanks a lot for including installation instructions for both CRAN and github. I believe the use of the `install_github` command requires that the `remotes` package is attached first. How about this:

> The latest development version can be installed from github with the [remotes](https://cran.r-project.org/web/packages/remotes/index.html) package:

```r
library(remotes)
install_github("anwarbio/bioassays")
```

**Comment by anwarbio** [comment]
@tomsing1 

I have changed this in README. The sentence is now written as **The latest development version can be installed from github with the remotes package**
```
library(remotes)
install_github("anwarbio/bioassays")
```
