### ISSUE TITLE
[JOSS REVIEW] Contribution guidelines

### ISSUE THREAD

**Issue by tomsing1** [anwarbio/bioassays#3]
Please add some simple Community guidelines: for third parties wishing to

1. Contribute to the software
2. Report issues or problems with the software 
3. Seek support

You can add these instructions in a [CONTRIBUTIONS.md file](https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors#examples-of-contribution-guidelines).

For inspiration, [here](https://github.com/jdblischak/workflowr/blob/master/CONTRIBUTING.md) is a an example from the [workflowr](https://github.com/jdblischak/workflowr) package.

**Comment by anwarbio** [comment]
@tomsing1 ,

Thank you for helping with this. I have now added a  `CONTRIBUTIONS.md`  file.
