### ISSUE TITLE
plate2df function not working properly

### ISSUE THREAD

**Issue by ghost** [anwarbio/bioassays#6]
I imported data with `readxl` and converted it to plate format using `data2plateformat`. I got a variable with all the numbers (when checking with `typeof()` it is a list, when checking with `class()` it is "tbl_df"  "tbl"  "data.frame") and then wanted to convert that to a data frame using `plate2df`, but I got a dataframe with no values (where the number is supposed to be, it is a NA). Row, col, and position are filled in correctly. 

I attached the corresponding data file and the code and the result is below:
```
OD_raw <- read_excel("96well_plate.xlsx")
OD_plate <- data2plateformat(OD_raw, platetype = 96)
OD_df <- plate2df(OD_plate); head(OD_df)

head(OD_df)
  row col position value
1   A   1      A01    NA
2   A   2      A02    NA
3   A   3      A03    NA
4   A   4      A04    NA
5   A   5      A05    NA
6   A   6      A06    NA
```
Thanks for your help.

Best, Ana

[96well_plate.xlsx](https://github.com/anwarbio/bioassays/files/9487908/96well_plate.xlsx)

**Comment by anwarbio** [comment]
Hi Ana,

The problem is with the way you read the excel file. The below code will
work.

OD_raw <-  as.data.frame (read_excel ("96well_plate.xlsx", col_names=
FALSE))
OD_raw <- OD_raw [-1, ]
OD_plate <- data2plateformat(OD_raw, platetype = 96)
OD_df <- plate2df(OD_plate); head(OD_df)

Thanks,
Anwar
